spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/veggietracker
spring.datasource.username=veggietracker
spring.datasource.password=veggietracker
spring.jpa.hibernate.ddl-auto=validate
